-- (C) 2024 Michael Lindenau licensed via https://www.gnu.org/licenses/agpl-3.0.txt
-- and https://toent.ch/licenses/AI_DISCLOSURE_LICENSE_V1
-- Not allowed to be used as AI training material without explicite permission.
-- Admin content providing full GV$SQL content
CREATE OR REPLACE VIEW sosl_session_sql_admin_v
AS
  SELECT inst_id
       , sql_text
       , sql_fulltext
       , sql_id
       , sharable_mem
       , persistent_mem
       , runtime_mem
       , sorts
       , loaded_versions
       , open_versions
       , users_opening
       , fetches
       , executions
       , px_servers_executions
       , end_of_fetch_count
       , users_executing
       , loads
       , first_load_time
       , invalidations
       , parse_calls
       , disk_reads
       , direct_writes
       , direct_reads
       , buffer_gets
       , application_wait_time
       , concurrency_wait_time
       , cluster_wait_time
       , user_io_wait_time
       , plsql_exec_time
       , java_exec_time
       , rows_processed
       , command_type
       , optimizer_mode
       , optimizer_cost
       , optimizer_env
       , optimizer_env_hash_value
       , parsing_user_id
       , parsing_schema_id
       , parsing_schema_name
       , kept_versions
       , address
       , type_chk_heap
       , hash_value
       , old_hash_value
       , plan_hash_value
       , full_plan_hash_value
       , child_number
       , service
       , service_hash
       , module
       , module_hash
       , action
       , action_hash
       , serializable_aborts
       , outline_category
       , cpu_time
       , elapsed_time
       , outline_sid
       , child_address
       , sqltype
       , remote
       , object_status
       , literal_hash_value
       , last_load_time
       , is_obsolete
       , is_bind_sensitive
       , is_bind_aware
       , is_shareable
       , child_latch
       , sql_profile
       , sql_patch
       , sql_plan_baseline
       , program_id
       , program_line#
       , exact_matching_signature
       , force_matching_signature
       , last_active_time
       , bind_data
       , typecheck_mem
       , io_cell_offload_eligible_bytes
       , io_interconnect_bytes
       , physical_read_requests
       , physical_read_bytes
       , physical_write_requests
       , physical_write_bytes
       , optimized_phy_read_requests
       , locked_total
       , pinned_total
       , io_cell_uncompressed_bytes
       , io_cell_offload_returned_bytes
       , con_id
       , is_reoptimizable
       , is_resolved_adaptive_plan
       , im_scans
       , im_scan_bytes_uncompressed
       , im_scan_bytes_inmemory
       , ddl_no_invalidate
       , is_rolling_invalid
       , is_rolling_refresh_invalid
       , result_cache
       , sql_quarantine
       , avoided_executions
       , heap0_load_time
       , heap6_load_time
       , result_cache_executions
       , result_cache_rejection_reason
    FROM gv$sql
;
GRANT SELECT ON sosl_session_sql_admin_v TO sosl_admin;
