SET TRIMSPOOL ON
SET LINESIZE 9999
SET NEWPAGE NONE
SET PAGESIZE 9999
-- limit CLOB display to 2000 char
SET LONG 4000
SET LONGCHUNKSIZE 4000
SET NULL 'NULL'
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
WHENEVER OSERROR EXIT FAILURE ROLLBACK
