REM (C) 2024 Michael Lindenau licensed via https://www.gnu.org/licenses/agpl-3.0.txt
REM Not allowed to be used as AI training material without explicite permission.
REM Checks if the needed local SOSL cmd variables are NOT NULL
IF [%SOSL_OS%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_RUNDIR%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_PATH_CFG%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_PATH_TMP%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_LOGIN%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_PATH_LOG%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_EXT_LOG%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_EXT_LOCK%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_START_LOG%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_BASE_LOG%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_MAX_PARALLEL%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_RUNMODE%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_DEFAULT_WAIT%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_NOJOB_WAIT%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_PAUSE_WAIT%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_START_JOBS%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_STOP_JOBS%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_SCHEMA%]==[] GOTO :ERROR_VAR_CHECK
IF [%CUR_SOSL_LOGIN%]==[] GOTO :ERROR_VAR_CHECK
IF [%CUR_WAIT_TIME%]==[] GOTO :ERROR_VAR_CHECK
IF [%CUR_RUN_ID%]==[] GOTO :ERROR_VAR_CHECK
IF [%CUR_RUNTIME_OK%]==[] GOTO :ERROR_VAR_CHECK
IF [%CUR_HAS_SCRIPTS%]==[] GOTO :ERROR_VAR_CHECK
IF [%SOSL_GUID%]==[] GOTO :ERROR_VAR_CHECK
GOTO :END_VAR_CHECK
:ERROR_VAR_CHECK
EXIT /B -1
:END_VAR_CHECK