@ECHO OFF
ECHO Timeframe within a day
SET SOSL_START_JOBS=12:00
SET SOSL_STOP_JOBS=18:00

SET CUR_RUNTIME_OK=0
SET CUR_TIME=13:00
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=17:59
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=18:01
CALL test_run_hours.cmd
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=23:59
CALL test_run_hours.cmd
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=03:30
CALL test_run_hours.cmd
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=11:59
CALL test_run_hours.cmd
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET SOSL_START_JOBS=00:01
SET SOSL_STOP_JOBS=23:59

SET CUR_RUNTIME_OK=0
SET CUR_TIME=03:59
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=23:59
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=00:01
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=11:59
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=12:30
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=21:45
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=00:00
CALL test_run_hours.cmd
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

ECHO Timeframe with daybreak
SET SOSL_START_JOBS=18:00
SET SOSL_STOP_JOBS=04:00

SET CUR_RUNTIME_OK=0
SET CUR_TIME=21:45
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=02:45
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=00:00
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=18:01
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=03:59
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=04:01
CALL test_run_hours.cmd
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=14:45
CALL test_run_hours.cmd
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET SOSL_START_JOBS=23:00
SET SOSL_STOP_JOBS=11:00

SET CUR_RUNTIME_OK=0
SET CUR_TIME=10:00
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=04:33
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=23:19
CALL test_run_hours.cmd
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=14:45
CALL test_run_hours.cmd
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=11:01
CALL test_run_hours.cmd
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR

SET CUR_RUNTIME_OK=0
SET CUR_TIME=22:55
CALL test_run_hours.cmd
IF NOT %CUR_RUNTIME_OK%==0 ECHO Result %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: OK
IF %CUR_RUNTIME_OK%==0 ECHO Result  %CUR_RUNTIME_OK% Timeframe %SOSL_START_JOBS% - %SOSL_STOP_JOBS%, current time %CUR_TIME%: ERROR
